# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-cb4-git
KERNEL_VERSION=4.9.0-rc7-sunxi-next-1-g096343ed-dirty

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}

  echo "NOTE: Using this kernel requires an updated U-Boot!"
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}
